### ISSUE TITLE
performRequest hangs ios14 Simulator -> App Store Rejection (use ios13 simulator)

### ISSUE THREAD

**Issue by se09deluca** [invertase/react-native-apple-authentication#141] opened 2020-09-22 09:40 UTC
**[:point_down: SEE [COMMENTS BELOW](https://github.com/invertase/react-native-apple-authentication/issues/141#issuecomment-697408152) TO UNDERSTAND STATUS / GET YOUR APP APPROVED :point_down:]**

Hi,
i've been experiencing this error from iOS 14.

I'm using @invertase/react-native-apple-authentication@**1.1.2** as i don't need Apple Signin for Android.

Although, in past AppleStore reviewers rejects my app randomly, probably depending on who tests the app, this time there's no way to make it accepts.

`       
 const appleAuthRequestResponse = await appleAuth.performRequest({
            requestedOperation: AppleAuthRequestOperation.LOGIN,
            requestedScopes: [AppleAuthRequestScope.EMAIL, AppleAuthRequestScope.FULL_NAME],
        });
`

It's a pity, this package works perfectly for real devices! 
Could you suggest me, what to do? It's a problem experienced only in my case or not only?

My React Native info

> System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 671.25 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.0, 29.0.2, 29.0.3
      System Images: android-19 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    create-react-native-module: 0.16.0
    react-native-cli: 2.0.1

**Comment by ferran9908** [comment] 2020-09-22 12:27
Same Issue. How do we circumvent this?

**Comment by mikehardy** [comment] 2020-09-22 13:22
That's odd, I have gotten it to work, and while I am currently working through a different apple store rejection it is related to a subsequent network load failing.

Honestly - and this is just supposition and I'm a bit frustrated by it and other issues I and others have with the apple testers - I think their network is crap. I think it's slow, and lossy, and drops connections. It's the only underlying reason I can think of for the variety of failures I see related to App Store approval.

**Comment by mikehardy** [comment] 2020-09-22 13:24
Two things, to move on from my frustration comment, and start fixing this:

1. Do not remain on old versions. It does not matter what you need or don't need. Bugfixes always come in new versions.
1. Can you reproduce this on the simulator on your local machine? Stated differently: Can you build and run the example from master on your machine, and it authenticates correctly on your local machine in an ios14 simulator? Because this works for me

**Comment by rafaismyname** [comment] 2020-09-22 17:33
Currently facing the same issue.
It was working on simulator before I upgrade from 1.1.2 to 2.0.1. Also I upgraded Xcode from 11 to 12.
No console output with any errors.

**Comment by gkothe** [comment] 2020-09-22 19:13
Same problem, perform request does not resolve.  It gets stuck on the password. I tried to enable and disable "sing in with apple" at sugested here => https://github.com/invertase/react-native-apple-authentication/issues/117, but made no difference.
IOS 14 e xcode 12.
tried with 1.1.2 and 2.01
![image](https://user-images.githubusercontent.com/11322245/93926617-1ef4d800-fcee-11ea-93a9-203d649bdf6e.png)

**Comment by dburdan** [comment] 2020-09-23 02:00
I also ran into this with iOS 14 but I think the issue is upstream. If I'm logged into iCloud in my iOS 14 simulator and go to icloud.com in Safari, the "Continue with Password" dialog that appears will also fail.

Curious if the icloud.com process fails for you all as well.

**Comment by ferran9908** [comment] 2020-09-23 05:45
> Same problem, perform request does not resolve. It gets stuck on the password. I tried to enable and disable "sing in with apple" at sugested here => #117, but made no difference.
> IOS 14 e xcode 12.
> tried with 1.1.2 and 2.01.
> I cant get to the log "appleAuthRequestResponse"
> ![image](https://user-images.githubusercontent.com/11322245/93926617-1ef4d800-fcee-11ea-93a9-203d649bdf6e.png)

From what I've seen, I get the same issue in the iOS 14 Simulator but not in the iOS 13 Simulator with the same code.

But then, I'm able to go past this screen on a physical iOS 14 device. 

This makes testing the app even harder. Is there any fix for this?

**Comment by mikehardy** [comment] 2020-09-23 14:04
There is no fix. I reproduce the problem.
For now assume the iOS14 simulator is broken.
The code works on iOS13 simulators. It works on iOS 13 and 14 real devices.

There is nothing we can do, I don't think.

If someone attempted it with Xcode 12.2beta or iOS simulators >=14.1 that would be instructive.

If anyone has anything new to add that will help, otherwise further "me too" posts won't advance the conversation - you can just use reactions if it's affecting you, but it's a known problem at this point

**Comment by anthlasserre** [comment] 2020-09-24 15:49
Just found what's going wrong. I had the same bug too since a recent upgrade of the lib and RN.
I think some call changed.

Previously I did:
```javascript
import appleAuth, {
  AppleAuthRequestOperation,
  AppleAuthRequestScope,
  AppleAuthCredentialState,
} from '@invertase/react-native-apple-authentication';
...
const { user, email, fullName } = await appleAuth.performRequest({
    requestedOperation: AppleAuthRequestOperation.LOGIN,
    requestedScopes: [AppleAuthRequestScope.EMAIL, AppleAuthRequestScope.FULL_NAME],
});
...
if (credentialState === AppleAuthCredentialState.AUTHORIZED) {
    // @XXX Waiting Apple Review
}
```

But theses elements are not exported from the lib: [AppleAuthRequestOperation, AppleAuthRequestScope, AppleAuthCredentialState]. I just checked and you have now to pass by `appleAuth` directly.

Like this:
```javascript
import appleAuth from '@invertase/react-native-apple-authentication';

const { user, email, fullName } = await appleAuth.performRequest({
        requestedOperation: appleAuth.Operation.LOGIN,
        requestedScopes: [appleAuth.Scope.EMAIL, appleAuth.Scope.FULL_NAME],
});
...
if (credentialState === appleAuth.State.AUTHORIZED) {
    // @XXX Waiting Apple Review
}
...
```

**Comment by mikehardy** [comment] 2020-09-24 16:26
@anthlasserre I believe you are conflating things. Certainly there were changes from v1.x of this lib to recently released v2.x but I for instance am using TypeScript. I'm not having any export or symbol declaration issues. I am using the symbols correctly because Typescript makes it so there is no other way. Yet I still reproduce the problem on simulator.

**Comment by artmerlop** [comment] 2020-09-26 17:52
> There is no fix. I reproduce the problem.
> For now assume the iOS14 simulator is broken.
> The code works on iOS13 simulators. It works on iOS 13 and 14 real devices.
> 
> There is nothing we can do, I don't think.
> 
> If someone attempted it with Xcode 12.2beta or iOS simulators >=14.1 that would be instructive.
> 
> If anyone has anything new to add that will help, otherwise further "me too" posts won't advance the conversation - you can just use reactions if it's affecting you, but it's a known problem at this point

@mikehardy I tested it on Xcode 12.2 beta and iOS 14.2 simulator, same issue.

**Comment by artmerlop** [comment] 2020-09-26 18:48
@mikehardy if you download iOS 13.6 simulator on Xcode > 12 you can test everything.

**Comment by se09deluca** [comment] 2020-09-26 19:56
Hi guys, thanks everyone for the replies.
Yes, the problem still exists on iOS 14 simulators, but apparently it doesn't come from the react-native-apple-authentication package.
I just found this [Apple forum thread](https://developer.apple.com/forums/thread/651533). It is an issue reported by many native iOS developers and attributed to Xcode 12, this bug already existed in the beta, but has not been fixed yet.

Hope it gets fixed by Apple soon.


-------
@mikehardy in my case, it doesn't works even in the example application, running on iOS 14. However in the meantime that the problem is solved, i'll upgrade the library version to benefit of the newest bug fixes.

Thank you @anthlasserre for the suggestion, but when i wrote this issue, i was on the 1.1.2 version of the package and the code was right for that version. Thank you anyway for the check!

**Comment by ihsanktmr** [comment] 2020-10-05 11:10
I am having the same problem. The error i get is;

`Error: The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error 1001.)`

Still no solution ?

**Comment by mikehardy** [comment] 2020-10-05 14:54
@ihsanktmr let us know what you find when you look for a solution, as you can see here, we have no new information.

**Comment by artmerlop** [comment] 2020-10-05 17:30
> I am having the same problem. The error i get is;
> 
> `Error: The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error 1001.)`
> 
> sign with apple on ios14 device works, ios14 simulator does not work. And app store keeps rejecting my app
> Still no solution ?

@ihsanktmr you should download iOS 13.X simulator and test on that version, also when you send it to review specify that apple signin function will not work on iOS 14 simulator, because it's a bug from Apple, reported by many developers, I specified that and my app got aproved.

**Comment by MrVanosh** [comment] 2020-10-10 19:32
I have similar issue with iOS 14 on simulator but I get this Error:
[Error: AppleAuth is not supported on the device. Currently Apple Authentication works on iOS devices running iOS 13 or later. Use 'AppleAuth.isSupported' to check device is supported before calling any of the module methods.]

**Comment by Vluf** [comment] 2020-10-14 08:51
@artmerlop I'm getting the same `The operation couldn't be completed` error on an iOS 13.5 simulator

**Comment by mikehardy** [comment] 2020-10-14 16:49
@Vluf I tested an iOS13.5 emulator just last night, worked fine for me --> 🤷  - not that helpful but is a success report. 13.5 seems to work fine in my testing. 14 simulator definitely still not working for me, but on device everything is fine

**Comment by Vluf** [comment] 2020-10-15 07:30
@mikehardy You're right, my error was due to a misconfiguration.

**Comment by mikehardy** [comment] 2020-10-15 14:29
I'm going to close this as there is no action to take I don't think.
In app store review comments you should note for reviewers that if they test apple sign in, it is broken on ios14 simulators and they must use either a real device or ios13

**Comment by jaysoni9294-1** [comment] 2020-11-12 10:27
in my case, it is not working on ios 14 real devices too

**Comment by KantaP** [comment] 2020-12-03 06:06
iOS 14 is not working

**Comment by mikehardy** [comment] 2020-12-03 11:42
@KantaP not my experience on real devices. On real devices it works for me. Prove it with a reproduction based on the example app, and if you can, open a new issue with full details please

**Comment by ithustle** [comment] 2020-12-14 20:25
@mikehardy , I'm using xcode 12.2 and simulator 14.2 and still the same.

**Comment by mikehardy** [comment] 2020-12-14 21:34
Yep, still working on real devices and ios13 just fine, still busted on ios14 simulator

**Comment by ithustle** [comment] 2020-12-17 11:07
I've tried right now on iOS 14.3 and still

**Comment by mikehardy** [comment] 2020-12-17 15:38
Thanks @ithustle - shameful really isn't it? :laughing: - ios13 simulators to test this continues to be the rule :shrug:

**Comment by htuzel** [comment] 2021-01-22 09:23
It is not only for the simulator. It happens on physical devices, too. My code is working well with ios 13 but for ios 14 it hangs on simulator and physical device (I am using test flight.)

Also, my application is rejected because of that.

**Comment by mikehardy** [comment] 2021-01-22 14:07
You may have a different problem. No other person has reported a problem on real devices.

**Comment by Omi-Navagis** [comment] 2021-02-05 02:36
This code was working fine while developing (even on real device).
```
 const appleAuthRequestResponse = await appleAuth.performRequest({
        requestedOperation: appleAuth.Operation.LOGIN,
        requestedScopes: [appleAuth.Scope.EMAIL, appleAuth.Scope.FULL_NAME],
});
```

But suddenly occur an Error when I run the same code on the app installed via Testflight.

And noticed that `Sign in with Apple` option is (debug) as on screenshot.

Does this making the issue?
Any opinion or any solution, thank you.
<img width="1094" alt="スクリーンショット 2021-02-05 11 23 17" src="https://user-images.githubusercontent.com/48199679/106981334-30261900-67a5-11eb-90ff-a7fa0860cce3.png">

**Comment by mikehardy** [comment] 2021-02-24 13:47
This is apparently still possible so I will re-open this.

Please note we have zero reproduction scenarios for this, and it works in testing on real ios14 devices as recently as a few hours ago for me when attempted to reproduce, so there will be no forward progress.

In order to move this forward we will need concrete information on exactly how to reproduce it.

**Comment by cylim** [comment] 2021-03-26 00:53
I was having the issues, but downgrading the package to v1.0.0 seems working.

**Comment by mikehardy** [comment] 2021-03-26 12:42
@cylim great you can reproduce it!

> In order to move this forward we will need concrete information on exactly how to reproduce it.

Please post a reproduction and we can move forward, otherwise there's no progress just notifications from github....

**Comment by cylim** [comment] 2021-03-27 02:49
@mikehardy I just tried to run it again with latest and v1.0.0. 

When I am using v1.0.0, the Apple Login proceed to next step.
When I am using the latest, it just stopped. Never proceed to next step.

### Code,
```js
// Failed latest
const appleAuthRequestResponse = await appleAuth.performRequest(
          {
            requestedOperation: appleAuth.Operation.LOGIN,
            requestedScopes: [
              appleAuth.Scope.EMAIL,
              appleAuth.Scope.FULL_NAME,
            ],
          },
          )
          
 // Success v1.0.0
 const appleAuthRequestResponse = await appleAuth.performRequest(
          {
            requestedOperation: AppleAuthRequestOperation.LOGIN,
            requestedScopes: [
              AppleAuthRequestScope.EMAIL,
              AppleAuthRequestScope.FULL_NAME,
            ],
          },
        )
```


### Video
v1.0.0 : https://www.youtube.com/watch?v=ajSujhM_Loo
latest : https://www.youtube.com/watch?v=8O5P1c9oEh4

**Comment by mikehardy** [comment] 2021-03-29 14:02
@cylim great findings! So when you bisect between the version that works and does not work, which commit is the culprit?

**Comment by cylim** [comment] 2021-03-30 00:29
@mikehardy Unsure. I didn't look into the source code yet, might try to check it today, busying with work. 😢 

The reason why I downgrade the version it due to my previous app using v1.0.0 is working, but new app using the latest is not working on iOS 14 real devices. 

If someone is in rush to get a fix, downgrade the version. We will look into what is causing it. 😄

**Comment by mikehardy** [comment] 2021-03-30 01:22
I think you have something else going on, not working on ios14 real devices is not something I reproduce. Current version works ios14 real devices for me. Not sure if your experience will be representative. I'd check it with the example app.

**Comment by birdwell** [comment] 2021-04-29 13:08
I have iOS 14.4.2 on a real device with xcode 12.4. When logging in with apple, there is no error logged on xcode or in the debugger. It goes through the whole process and closes but then response from performRequest never fulfills. @mikehardy 
```
      const appleAuthRequestResponse = await appleAuth.performRequest({
        requestedOperation: appleAuth.Operation.LOGIN,
        requestedScopes: [appleAuth.Scope.EMAIL, appleAuth.Scope.FULL_NAME],
      });
```

**Comment by birdwell** [comment] 2021-04-29 18:04
> I think you have something else going on, not working on ios14 real devices is not something I reproduce. Current version works ios14 real devices for me. Not sure if your experience will be representative. I'd check it with the example app.

What version of Xcode are you running?

**Comment by MariaFF** [comment] 2021-05-20 18:06
Hi guys,
I'm not sure to report my problem here, I'm sorry about anything.
I'm having a problem on the real device SO 14.4.2, I'm also using TestFlight, after setting the password, this stuck on loading. Version lib 2.1.2
@htuzel did you get solve this ?

**Comment by htuzel** [comment] 2021-05-20 18:47
You need to enable apple signin for your build (not only for debugging).
It was the issue for my case.

**Comment by DKbyo** [comment] 2021-06-21 16:27
I had same issue, but I rewrote my code to use `.then` and found that my issue was caused because I didn't follow the [Migration Guide](https://github.com/invertase/react-native-apple-authentication/blob/master/docs/MIGRATION.md) since some constants were renamed.  After follow the migration guide all was working again.

It seems that React Native + async is not handled correctly the errors and you cannot see what is happening.

**Comment by UsamaAshraf82** [comment] 2021-07-27 14:09
It is happening with me working on v13 Simulator and Device but not Working on v14 Simulator and Real Device Also
using library version v2.1.2

**Comment by mikehardy** [comment] 2021-07-27 14:58
@UsamaAshraf82 it is working on a real device with iOS 14, I just re-tested it literally this moment to make sure before asserting it works on real device with iOS 14.

Not working on iOS14 simulator is a known issue with no workaround, out of control of this library

But if it is not working on a real device with iOS 14 for you, you should examine your project - I suspect something is not configured correctly for you and it is almost certainly project-specific

**Comment by StijnCoolen** [comment] 2021-12-07 14:42
@mikehardy you mention that it should work on simulators (if not iOS 13), while the following is mentioned in the docs:
```
// get current authentication state for user
// /!\ This method must be tested on a real device. On the iOS simulator it always throws an error.
const credentialState = await appleAuth.getCredentialStateForUser(appleAuthRequestResponse.user);
```

Don't we need to call `appleAuth.getCredentialStateForUser ` for it to work? How can I know if a user is authorized without calling this method?

**Comment by mikehardy** [comment] 2021-12-07 14:57
It appears in the example we call it https://github.com/invertase/react-native-apple-authentication/blob/main/example/app.ios.js
However it also appears that it is not strictly necessary to work - you already have the identityToken at that point and can use it.

So, one API (the sign in ) and the other (the credential state) are related but orthogonal. 

You know the user is authorized if signin returned a token. That works on ios13 simulator, and real devices, for me.

You can then periodically check credential state if you like, but that's different from signin. It appears that does not work on simulators? I'm not sure, the simulators are so broken in so many ways and specifically for this library, that I don't find it tremendously useful to do more than check basic signin (on ios13) in my projects. I rely on real devices for testing.

**Comment by StijnCoolen** [comment] 2021-12-13 13:51
@mikehardy ok good to know. We are having issues getting our app approved by Apple and thought that it might have something to do with `appleAuth.getCredentialStateForUser` not working is simulators. Now that we have removed it, it is still being rejected unfortunately. I'll keep researching and will share here when I've got answers. Anything we can do in the meantime? We have tried to ask Apple to use io13 without any success.

**Comment by mikehardy** [comment] 2021-12-13 13:53
In my instructions I say: "use a real device, or an ios13 simulator". I don't have problems, but then apple review is notoriously hit or miss by common knowledge and in my experience. It feels like each time they review they fail something that they passed before, despite no changes. I wish I was not so cynical in this area as it would be more helpful, but with apologies, that's where I'm at personally with them. It's a farce and I can't offer much help beyond what we know here technically by observation: ios14 and ios15 emulators do not appear to work with apple sign in :shrug:

**Comment by renchap** [comment] 2022-06-24 10:09
According to [a comment in the Apple dev forum](https://developer.apple.com/forums/thread/651533?answerId=717307022#717307022), iOS 16 simulator fixes the issue.

If anybody running on the beta could confirm, it would be awesome news!

**Comment by mikehardy** [comment] 2022-06-24 15:06
@renchap OH MY $DEITY! You are right! They fixed it. They finally fixed it. After only around 2 years. Wow.
Confirmed working on Xcode 14 beta 1 (beta2 is downloading for me still)

Note credential state "authorized" in screen cap. Note that if you have never signed in to your apple account on the simulator your *first* attempt will fail with error 1000 still, because the flow does not work well with the case where a user is never signed in to the device at all but that's okay because it does not happen in practice on real devices.

Second attempt works.

![image](https://user-images.githubusercontent.com/782704/175563479-9145722f-8f70-4758-ba03-ab124e76bd38.png)

Xcode 14.0
Build version 14A5228q

**Comment by mikehardy** [comment] 2022-06-24 15:06
(do note that they messed up the button styles though: different issue, what can we do!? #286 )

**Closed by mikehardy** 2022-06-24 15:06 UTC
Labels: bug, apple-issue

**Comment by aramvr** [comment] 2023-09-16 18:19
I'm running on iOS 16.4 and still have the issue, I don't have the option to install the older iOS 13 version as it does not appear on the versions list. 
I will appreciate if someone can share a solution.

**Comment by nelsonhernandeztrd** [comment] 2024-10-29 16:30
I have a similar problem
