### ISSUE TITLE
unhandled promised rejection

### ISSUE THREAD

**Issue by Sumanth1124** [invertase/react-native-apple-authentication#264] opened 2022-03-08 18:46 UTC
I have run on iOS simulator. the version used is 15.2. though it is iOS 13 or later, it is not supporting. 
I have even tried running on device but throws the same exception. below is the error I got. can you please help me out

[Unhandled promise rejection: Error: AppleAuth is not supported on the device. Currently Apple Authentication works on iOS devices running iOS 13 or later. Use 'AppleAuth.isSupported' to check device is supported before calling any of the module methods.]
at node_modules/@invertase/react-native-apple-authentication/lib/AppleAuthModule.js:22:10 in throwIfNotSupported
at node_modules/@invertase/react-native-apple-authentication/lib/AppleAuthModule.js:104:23 in performRequest
at components/Login.js:16:41 in onAppleButtonPress
at components/Login.js:13:4 in onAppleButtonPress
at components/Login.js:91:73 in Pressable.props.onPress
at node_modules/react-native/Libraries/Pressability/Pressability.js:697:17 in _performTransitionSideEffects
at node_modules/react-native/Libraries/Pressability/Pressability.js:634:6 in _receiveSignal
at node_modules/react-native/Libraries/Pressability/Pressability.js:528:8 in responderEventHandlers.onResponderRelease

**Comment by mikehardy** [comment] 2022-03-08 18:51
Does the example app work for you? If the example app works, the problem is in your project somewhere thus won't result in a change in this module

**Comment by Sumanth1124** [comment] 2022-03-08 19:05
you mean app.ios.js ??

**Comment by mikehardy** [comment] 2022-03-08 19:10
I mean the repository comes complete with an example app, use it to verify the module is working
https://github.com/invertase/react-native-apple-authentication/tree/main/example
(although to be clear, you'll get the correct "is supported" response, but the actual log in does not work unless you configure the ios simulator to use iOS13.x - it will work on a real device though)

And I'll give you a spoiler - the module works just fine for me in my project on simulator and real devices in my work projects, as well as the example project.

Something is wrong in your project, it will not result in a change here.

**Comment by Sumanth1124** [comment] 2022-03-08 19:46
I am getting the below error when I try to run using the command {npx react-native run-ios}

The following build commands failed:
        CompileC /Users/adupalasumanthreddy/Library/Developer/Xcode/DerivedData/RNAppleAuthentication-fkiywflfidnnpnbxsjouekizkary/Build/Intermediates.noindex/RNAppleAuthentication.build/Debug-iphonesimulator/RNAppleAuthentication.build/Objects-normal/arm64/RNAppleAuthButtonViewManager.o /Users/adupalasumanthreddy/Desktop/react-native-apple-authentication/ios/RNAppleAuthentication/RNAppleAuthButtonViewManager.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'RNAppleAuthentication' from project 'RNAppleAuthentication')
(1 failure)

**Comment by Sumanth1124** [comment] 2022-03-08 21:35
<img width="256" alt="Screen Shot 2022-03-08 at 4 32 34 PM" src="https://user-images.githubusercontent.com/41239232/157329057-c072ea1d-7716-4e4b-9ea4-b8efb81a3795.png">

this error has occurred while building. can you please look into it

**Comment by mikehardy** [comment] 2022-03-08 21:40
Yeah, turns out the example was still on react-native 0.61, it had not seen attention in quite some time. That old version has two serious problems, one being that it doesn't work well with Xcode 12.5+ and one being that it does not work on Apple Silicon / M1 macs (I realized that from your first error posting - that you were arm64, that was the build problem)

I just about have the example updated - https://github.com/invertase/react-native-apple-authentication/commits/%40mikehardy/dependency-updates - I just have a little bit more forward-porting to do then the example will work again

I will reiterate though: this works for me in work projects as recently as last week when I last tested it, this used to work the example, and no one else has reported this. The root cause here will be in your project somewhere.

As soon as I get the example up to date again and see with my own eyes that it's working, I will likely close this issue as "cannot reproduce"

**Comment by Sumanth1124** [comment] 2022-03-08 23:10
Thank you @mikehardy 
Is it updated?

**Comment by mikehardy** [comment] 2022-03-08 23:20
I'll post here as soon as it is, I want to make sure you understand the reality though, I need to update the example because the example needs to work, but:

> I will reiterate though: this works for me in work projects as recently as last week when I last tested it, this used to work the example, and no one else has reported this. The root cause here will be in your project somewhere.

> As soon as I get the example up to date again and see with my own eyes that it's working, I will likely close this issue as "cannot reproduce"

**Comment by mikehardy** [comment] 2022-03-09 00:16
Example update PR will merge as soon as CI is done, tested locally though it works.
You have a project-specific problem, it will not result in a change in this module, so this is resolved "cannot reproduce"

**Closed by mikehardy** 2022-03-09 00:16 UTC
