### ISSUE TITLE
Not getting User Object in Response Android Apple Login

### ISSUE THREAD

**Issue by rajatgyl** [invertase/react-native-apple-authentication#238] opened 2021-09-16 13:43 UTC
Please refer to the below issue I want to reopen it as I did not get any solution to this anywhere.....

https://github.com/invertase/react-native-apple-authentication/issues/237#issue-997038891

https://github.com/invertase/react-native-apple-authentication/issues/237#issuecomment-920913023

**Comment by mikehardy** [comment] 2021-09-16 13:48
I am traveling and have no time to solve your project problem, others seem to use it fine, sorry

**Comment by mikehardy** [comment] 2021-09-17 16:28
dupe of #237, conversation continued there

**Closed by mikehardy** 2021-09-17 16:28 UTC
