### ISSUE TITLE
Simulator ios 14 does not work

### ISSUE THREAD

**Issue by azesmway** [invertase/react-native-apple-authentication#162] opened 2020-11-06 17:15 UTC
Xcode Version 12.1 (12A7403)
Simulator iOS 14.1

authorization does not work and Apple rejects the application

**Comment by gilbertl** [comment] 2020-11-07 19:39
Having the same issue:

apple login stopped working recently. Apple store rejected our application.

I went back in time to our older version and it's also not working. It's possible there's some changes made on Apple's end that's causing this issue. 

Has anyone heard of any related issues?

**Comment by mikehardy** [comment] 2020-11-07 22:16
Duplicate of #141 - please search issues prior to logging new ones. They will pass the app if you tell the reviewers that they have to use ios13.x if they are verifying apple sign in on a simulator, or a real device for ios14.

**Closed by mikehardy** 2020-11-07 22:16 UTC

**Comment by c-info** [comment] 2022-12-02 06:09
Uses same
Xcode  Version 13.2.1 (13C100)
Simulator 13 pro max - iOS version 15.0 

still having same issue


> Duplicate of #141 - please search issues prior to logging new ones. They will pass the app if you tell the reviewers that they have to use ios13.x if they are verifying apple sign in on a simulator, or a real device for ios14.
