### ISSUE TITLE
Sign in with Apple stucks after inputting password 

### ISSUE THREAD

**Issue by vanminhnguyenbmt** [invertase/react-native-apple-authentication#159] opened 2020-10-31 09:50 UTC
Hi everyone,
We were able to use Apple sign in before the release of iOS 14.
But after the release of Xcode 12 and iOS 14, the function no longer works on devices with iOS 14.x **on both simulators and real devices**.
It just stops after inputting password and the spinning wheel runs infinitely and does not come back to our application, so the function `performRequest` has not been passed and we have not found out what's wrong.
```js
            appleAuth.performRequest({
                requestedOperation: appleAuth.Operation.LOGIN,
                requestedScopes: [appleAuth.Scope.EMAIL, appleAuth.Scope.FULL_NAME],
            });
```

We had checked again with simulator with ios 13.x and it still works.

Have anyone come up with the issue, please help?

Regards.

**Comment by mikehardy** [comment] 2020-10-31 12:20
Hi there! I think you need to be more specific, by which I mean Xcode 12 came out in form of 12, 12.0.1 and 12.1. It was widely documented here that simulator did not work on iOS 14 and it did not matter about Xcode. Real devices worked with 11.x and 12 12.0.1. I just updated to 12.1 and haven't tested a real device yet.

Also iOS 14 itself has more than one version, with the simulator now up to 14.1 and I forget the real device OS. 14.0.1 at least.

I haven't seen failures on device yet though, so please be specific about which exact pairings you've seen work and then with which pairings it fails if you can, that would help advance this - but so far no, no one else has reported this

**Comment by mathieupetrini** [comment] 2020-10-31 13:42
I have the same issue on simulator iOS 14.1 and XCode 12.1

![image](https://user-images.githubusercontent.com/6863446/97780821-42316380-1b87-11eb-8243-97dc3b7c63ba.png)

**Comment by mikehardy** [comment] 2020-10-31 14:10
@mathieupetrini ok, but that's just a continuation of the "sign in with apple doesn't work if simulator is > 13" issue, not the perhaps new "Xcode 12.x breaks sign in with apple on real devices". Your issue is well-documented here and has unfortunately existed since iOS14 release

**Comment by mathieupetrini** [comment] 2020-10-31 14:23
On real device it is working well.

Sorry for the inconvenience

**Comment by mikehardy** [comment] 2020-10-31 15:00
@mathieupetrini out of curiosity, what version of Xcode exactly, and iOS exactly are you using to build / run on real device? Might help advance this issue :-)

**Comment by mathieupetrini** [comment] 2020-10-31 15:03
XCode : 12.1
iOS Version : 14.0.1

**Comment by mikehardy** [comment] 2020-10-31 15:08
Excellent - those are current versions, so I'm going to say we can't reproduce this @vanminhnguyenbmt and close it - seems to work in my project and for @mathieupetrini so I suspect something not correct with your project somehow?

**Closed by mikehardy** 2020-10-31 15:08 UTC
Labels: question

**Comment by rahmanharoon** [comment] 2022-11-18 21:03
Did you fixed this issue

**Comment by mikehardy** [comment] 2022-11-18 21:34
This issue has been closed with no reproductions for more than 2 years

**Comment by rahmanharoon** [comment] 2022-11-19 05:42
I have facing this issue on xcode with version `14.1`

**Comment by mikehardy** [comment] 2022-11-19 23:08
@rahmanharoon https://stackoverflow.com/help/how-to-ask

Is that Xcode version 14.1? What iOS version? real device or simulator? what version of the module? etc etc
