### ISSUE TITLE
how about react native 0.59

### ISSUE THREAD

**Issue by DungBuiDeveloper** [invertase/react-native-apple-authentication#8] opened 2019-12-10 01:55 UTC
can you using react native < 0. 6 support please?

**Comment by mikehardy** [comment] 2019-12-10 03:20
This is not and cannot be possible unfortunately.
It is not a policy decision ("we do not want to support that") it is a technical limitation.

Specifically: 
- Sign in with Apple requires ios13 or higher
- Okay, then ios13 requires Xcode 11 or higher
- Okay, Xcode 11 requires react-native 0.60 or higher

That is the chain of requirements

If you can find a way to make Xcode 11 + iOS 13 work with react-native 0.59 okay, but as far as I know they are incompatible, with no interest to work on them.

I sympathize. The move from 0.59 to 0.60 is not fun. Hopefully https://react-native-community.github.io/upgrade-helper/ can help, and jetifier (which I helped author: I really do sympathize with bridging this gap!) can help. But it's time to move I think, if you need apple sign in.

I'm closing this because of the reasons above but maybe there is a way for RN0.59 + Xcode 11 + iOS 13? If so we can reopen.

**Closed by mikehardy** 2019-12-10 03:20 UTC

**Comment by nicolasdet** [comment] 2020-02-19 16:37
Hello, react-native 0.59.9 and 0.59.10 support Xcode 11. 
i'm actually working on an react-native 0.59.9 app  (on Xcode 11+) and I wanted to know if someone had managed to run this library with RN 0.59.9.
ps: i know that migrating to react-native 0.60 is important.. but i don't think we will got time to do this since April 2020..

**Comment by Nordzisko** [comment] 2020-03-22 21:49
@nicolasdet did you manage to run this library under RN 0.59.10 ?

**Comment by nhnam** [comment] 2020-03-25 02:52
This library works perfectly on RN 0.59, Xcode11, iOS13. we are using in our project.

**Comment by zumaawad** [comment] 2020-03-29 18:11
@nhnam How you solve the issues in RNAppleAuthUtils.m file ?!

**Comment by nhnam** [comment] 2020-03-30 02:29
> @nhnam How you solve the issues in RNAppleAuthUtils.m file ?!

Do you mention about this issue? https://github.com/invertase/react-native-apple-authentication/pull/50/files

**Comment by aravi365** [comment] 2020-05-09 05:20
> This library works perfectly on RN 0.59, Xcode11, iOS13. we are using in our project.

Can you explain the manual installation flow?

**Comment by nicolasdet** [comment] 2020-05-28 09:36
I mannaged to make work library under RN 0.59.9
- yarn add @invertase/react-native-apple-authentication
- react-native link @invertase/react-native-apple-authentication
- cd ios && pod install 

Dont forget to make to make this part : [Environment Setup](https://github.com/invertase/react-native-apple-authentication/blob/master/docs/INITIAL_SETUP.md)

**Comment by Knight704** [comment] 2020-06-19 11:06
I confirm that with RN 0.59.4 it works ok, thanks @nicolasdet 
At first when I saw 0.60 requirement I was upset since we needed apple login ASAP, but searching through issues get me better ❤️

**Comment by BenAllenUK** [comment] 2020-07-21 12:12
I can confirm that this works for RN 0.59.9. I'm using Xcode 11.6, iOS 13.6 and version 1.1.2 of this library.

**Comment by erikponce1302** [comment] 2020-07-28 13:25
> I can confirm that this works for RN 0.59.9. I'm using Xcode 11.6, iOS 13.6 and version 1.1.2 of this library.

Hello @BenAllenUK , do you have the step by step? Because I'm integrating in my project with 
- Xcode Version 11.6 (11E708)
- React Native 0.59.9
- Version 1.1.2

After react-native link @invertase/react-native-apple-authentication my app crash.

I saw this video https://www.youtube.com/watch?v=IN9_XzX1iDg and he don't execute react-native link ...

**Comment by pavelprudnikov** [comment] 2020-08-15 21:13
> After react-native link @invertase/react-native-apple-authentication my app crash.
Try manual linking, it works for me

https://stackoverflow.com/a/52894280/1901277

**Comment by sinhpn92** [comment] 2021-01-16 07:25
Humzzz.
Have anyone facing this issue?
```Unable to find a specification for `React-Core` depended upon by `RNAppleAuthentication````

**Comment by mikehardy** [comment] 2021-01-16 14:13
Only when the react-native project is misconfigured
If you can reproduce with the example, let us know

**Comment by thainquet** [comment] 2021-01-18 03:48
> Humzzz.
> Have anyone facing this issue?
> ```Unable to find a specification for `React-Core` depended upon by `RNAppleAuthentication````

hi there, i found a workaround:
1. Navigate to `node_modules/@invertase/react-native-apple-authentication`
2. Find the `RNAppleAuthentication.podspec`
3. line 18: change 'React-Core' -> 'React/Core'
4. Save file then install again

I've test in react-native 0.59.2 and it works!
P/s: spent a morning for finding folder `react-native-apple-authentication`. It was inside @invertase folder instead of standing outside like other packages....

**Comment by mikehardy** [comment] 2021-01-18 13:58
There is no support at all for react-native versions that old. If you were using a version from within the last year, it would work without editing the .podspec. That said, make sure you're using patch-package to implement that change or you'll be very sad next time you run npm i / yarn as it will wipe out your change
