### ISSUE TITLE
Styling the button font and text size

### ISSUE THREAD

**Issue by nes123** [invertase/react-native-apple-authentication#105] opened 2020-07-05 14:29 UTC
Is it possible?

**Comment by mikehardy** [comment] 2020-07-05 16:33
duplicate of #104 (though admittedly, that one does not pop up in the searches you would normally do)
Apple does not allow you to change the style at all. They have very strict style guides and don't trust developers, because you have to admit, we are awful about changing UIs in general and you know Apple won't have that...

**Closed by mikehardy** 2020-07-05 16:33 UTC
