### ISSUE TITLE
AuthorizationError error 1001 when the user is not signed in with iCloud

### ISSUE THREAD

**Issue by AlexanderZaytsev** [invertase/react-native-apple-authentication#90] opened 2020-06-05 09:17 UTC
### How to reproduce

1. Sign out from iCloud on the simulator.
2. Calling `appleAuth.performRequest` will prompt a popup suggesting that the user signs into iCloud in the settings.

This results in `Error: The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error 1001.)`

### How to fix currently
```javascript
state = {
  isLoading: false
}

signIn = async () => {
  this.setState({isLoading: true})
  const appleAuthResponse = await appleAuth.performRequest(...)
}

onAppStateChange = nextAppState => {
  if (nextAppState == 'active' && this.state.isLoading) {
    // Call signIn again when the user returns to the app after signing into iCloud
    this.signIn()
  }
}

componentDidMount() {
   AppState.addEventListener('change', this.onAppStateChange)
}

componentWillUnmount() {
  AppState.removeEventListener('change', this.onAppStateChange)
}
```
So, basically the first `performRequest` will fail, that's why we listen to the AppState change event and when the user returns back to the app, we call `performRequest` again.

**Comment by mikehardy** [comment] 2020-06-05 15:32
Simulator only. Duplicate of a bunch in the repo already

**Closed by mikehardy** 2020-06-05 15:32 UTC

**Comment by hpbg7q6pyq-ops** [comment] 2026-03-05 07:55
Apple ID issue
