### ISSUE TITLE
The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error 1000.)

### ISSUE THREAD

**Issue by zaidraddad94** [invertase/react-native-apple-authentication#89] opened 2020-06-03 15:34 UTC
I have been stuck in this for a whole day, I have tried everything but still same error:
backend.js:32 Possible Unhandled Promise Rejection (id: 1):
Error: The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error 1000.)
Error: The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error 1000.)
    at Object.promiseMethodWrapper [as getCredentialStateForUser] (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3765:36)
    at AppleAuthModule.getCredentialStateForUser (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:419252:28)
    at _callee3$ (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:417505:91)
    at tryCatch (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:2302:19)
    at Generator.invoke [as _invoke] (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:2478:24)
    at Generator.prototype.<computed> [as next] (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:2345:23)
    at tryCatch (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:2302:19)
    at invoke (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:2378:22)
    at http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:2388:15
    at tryCallOne (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4841:14)

**Comment by kcotiasrp** [comment] 2020-06-04 14:03
Check if you've enabled **Sign-in With Apple** on Xcode Sign-in & Capabilities.

**Comment by AlexanderZaytsev** [comment] 2020-06-05 09:06
This error might also occur when the user is not signed in into iCloud.

**Comment by zaidraddad94** [comment] 2020-06-06 08:39
Capabilities it is enabled
the problem not with appleAuth 
its with AppleAuthCredentialState

**Comment by yasirwahid** [comment] 2020-06-07 20:13
@zaidraddad94 @AlexanderZaytsev  have you solved it? im getting an UNKNOWN error
 [Error: The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error 1000.)]
Capabilities is enabled.

const credentialState = await appleAuth.getCredentialStateForUser(user);
for me this command is not working.

**Comment by bochitan** [comment] 2020-06-11 07:38
i also get problem with below codes

const credentialState = await appleAuth.getCredentialStateForUser(user);

this command is not working althought i got data of appleAuthRequestResponse

**Comment by dackers86** [comment] 2020-06-11 08:55
Is it ok to close this one, looks to be a dupe of https://github.com/invertase/react-native-apple-authentication/issues/9?

**Comment by magrinj** [comment] 2020-06-18 19:25
As mentioned on the expo sign in package, similar to this one. `getCredentialStateForUser` will always failed on simulator, this method should only be used on real devices.

https://docs.expo.io/versions/latest/sdk/apple-authentication/#appleauthenticationgetcredentialstateasyncuser

Maybe a quick quote can be added in the documentation.

**Comment by mikehardy** [comment] 2020-06-18 20:02
Good find @magrinj ! PRs happily accepted - the github PR workflow for docs is super-easy + quick, all in browser

**Comment by magrinj** [comment] 2020-06-18 20:03
@mikehardy I'll make a PR :)

**Comment by magrinj** [comment] 2020-06-18 20:25
Done on #97 🙂

**Closed** 2020-06-23 15:05 UTC

**Comment by yorlandmurillo** [comment] 2020-07-16 18:42
> Check if you've enabled **Sign-in With Apple** on Xcode Sign-in & Capabilities.

Thank you! This was my problem!

**Comment by papay0** [comment] 2020-09-01 23:37
> As mentioned on the expo sign in package, similar to this one. `getCredentialStateForUser` will always failed on simulator, this method should only be used on real devices.
> 
> https://docs.expo.io/versions/latest/sdk/apple-authentication/#appleauthenticationgetcredentialstateasyncuser
> 
> Maybe a quick quote can be added in the documentation.

How do we get Apple to approval the app then? :)
They test on a simulator and they keep telling me that it doesn't work on their simulator.
It works perfectly on my devices.

**Comment by mikehardy** [comment] 2020-09-01 23:43
Perhaps if you are on a simulator, don't call that method? https://github.com/react-native-community/react-native-device-info/#isemulator

I mean, that's silly but it can get you through. I personally don't use that method so I pass review - if you avoid it on simulators you might make it

**Comment by Singh-KiaTec** [comment] 2020-10-23 15:37
Check if the user has signed in in ICLOUD.

**Comment by dgreen-dev** [comment] 2021-07-12 14:30
I'm facing the same issue on release build at test flight and It's working fine on debug mode, apple sign-in enable from XCode and identifier as well

**Comment by iqbalhusen** [comment] 2021-07-12 15:11
<img width="1680" alt="Screenshot 2021-07-12 at 20 22 43" src="https://user-images.githubusercontent.com/7779721/125311567-2191ee00-e351-11eb-8d2e-e4ec590f4c2a.png">

In my case, the "Sign In with Apple" capability is missing. Sorry, I am new to iOS development. What do I need to do in order to make this capability available on my app?

**Comment by mmkhmk** [comment] 2023-09-11 05:19
Is it possible to distinguish between errors caused by misconfigurations in Xcode settings and errors that occur when the user is not signed in to iCloud?
