### ISSUE TITLE
Credential status always REVOKED in ios18+ Simulator / have to use iOS17 Simulator

### ISSUE THREAD

**Issue by gabemeola** [invertase/react-native-apple-authentication#356] opened 2024-10-27 19:23 UTC
In ios 18, calling `appleAuth.getCredentialStateForUser(userId)` always returns REVOKED (0)

**Comment by KamranZafar19** [comment] 2024-11-04 09:36
@gabemeola have find out the solution?

**Comment by hgrami** [comment] 2024-11-13 15:42
@gabemeola any solution yet anyone?

**Comment by mikehardy** [comment] 2024-11-13 17:07
I see revoked in the Simulator but it works on device
I couldn't figure out any reason for it, all I can think of is that it is (yet another) Simulator vs real device difference
In my experience you cannot rely on the Simulator for the final say in Apple testing, and especially with apple auth

Unfortunately, I believe Apple tests apps on Simulators when submitted to the App Store, so you do have to handle it.

Has anyone experienced this on real devices, or like me just simulator only ?

**Comment by eyupkoc29** [comment] 2024-11-19 08:11
There is a problem with iOS 18.1, I am testing it on iPhone 13 mini, the credential state is revoked. For this reason, the application is not approved.

[Apple Sign In] Credential State: 0

**Comment by eyupkoc29** [comment] 2024-11-19 15:02
> sorry for being very very precise here: but I assume when you say "iPhone 13 mini" you mean "a real physical iPhone 13 mini device", that is you do not mean "an iOS simulator iPhone 13 mini"
> 
> I think what you wrote is pretty clear but I have to make sure, because I tested on a real iPhone SE2 device and it seemed I got the correct credential state using the test app in this repository. I only saw the (bizarre, to me) revoked credential on the test app in the simulator.


I encountered this issue on the simulator, and since I don’t have an iPhone 13 Mini for physical testing, I couldn’t verify it properly. As a result, the app was rejected on the App Store.

**Comment by mikehardy** [comment] 2024-11-19 16:03
Ah ha! I am really glad I asked then. As far as I can see, the simulator *always* returns revoked for the credential right now (testing iOS 18.1 / current as of this typing). I have no idea why, anyone that looks on stackoverflow or in the apple issue tracker and posts information would be a hero.

Also, anyone that tested various iOS versions to see how they respond would also be a hero. I *believe* (but needs confirmation) that this was working in iOS 16.x and iOS 17.x. I am not sure about 18.0. 18.1 appears to always have the credential revoked.

Note that on a real device it works, I tested the example app without changes on an iOS 18.1 simulator and an iOS 18.1 iPhone SE2 real device and I got credential revoked on simulator and credential ok on real device.

I can only explain that by assuming the iOS 18.1 simulator has a bug.

If we can determine a version that works, you can leave instructions in your app submission to test with a specific version that works (like, 17.whatever), and they should accept that, especially if you link an apple developer forum issue where others document + discuss the issue.

**Comment by mikehardy** [comment] 2024-11-19 20:01
That just confirms (for me at least) this is yet-another-apple-authentication-simulator bug. Which is really hard to deal with because the Apple employees use the Apple Simulator for App Review. And Apple *requires* Sign-In With Apple in your App if you allow any social auth (which everyone does...). So this just blocks everyone.

Last time that happened we all had to put specific instructions in the App Review submission notes telling the reviewers to use a specific Simulator iOS version and why. We'll likely have to do the same here if this is affecting you but first we need someone to determine the last known-good version of iOS for the simulator. Also we'll need to determine if the credential revocation really matters - maybe you can just code around it? It does log you in after all, just with a revoked credential...and you can tell you are on the Simulator I think...

**Comment by mikehardy** [comment] 2024-11-20 18:00
Okay, I checked it today.
The iOS17 emulators work fine for credential status.
iOS18/18.1 simulators are broken, they will always return credential status revoked

As a workaround, if your app can detect it is on a simulator and is an affected version (for instance, with react-native-device-info [isEmulator](https://github.com/react-native-device-info/react-native-device-info/#isemulator) and [getSystemVersion()](https://github.com/react-native-device-info/react-native-device-info/#getsystemversion)) then you can ignore that and proceed as normal, so your app will pass review.

Alternatively, you may instruct the reviewer that credential revocation status is incorrect on iOS18/18.1 and testing must be performed on an iOS17 simulator

<img width="576" alt="image" src="https://github.com/user-attachments/assets/bee10b36-d7dc-4b81-99ae-cc1f4bbc67a6">

I have pinned this issue and updated the title to hopefully help others
However this is not actionable here at all, so I will close it - I understand it isn't fixed but we can't fix it, we can only workaround broken Simulators. Not the first time, won't be the last I'm sure

**Closed by mikehardy** 2024-11-20 18:00 UTC

**Comment by mikehardy** [comment] 2024-11-20 18:08
I opened a developer forum thread here, waiting to be approved+published at the moment but hopefully will be visible soon: https://developer.apple.com/forums/thread/769231

I have not logged an issue or anything but perhaps someone else could and they could comment? The issue is closed because it is not really actionable but sharing useful information is encouraged.

Please please please no "me too"s or "+1"s though, those are notification spam. Just add to the conversation if you are really moving it forward with new information. Thanks

**Comment by hpbg7q6pyq-ops** [comment] 2026-01-13 10:38
Credential always REVOKED ios18+ simulator (workaround:use ios17 or ignore status)on jaunary13,2026
