### ISSUE TITLE
Different behaviour in simulator and real device

### ISSUE THREAD

**Issue by kindacoder** [invertase/react-native-apple-authentication#74] opened 2020-05-05 11:04 UTC
Hi Team, 
I am trying to implement Apple sign in into my app. Whenever I click on the Apple logo, I am able to see the popup below. No matter how many times I am logging in, I am getting the same popup.
 
![Screenshot 2020-05-05 at 4 26 31 PM](https://user-images.githubusercontent.com/28186433/81059157-8bad3880-8eed-11ea-8282-cb5169730213.png)

But behavior changes in the real device.
on first click, the user is getting the popup above but on subsequent click, below popup is showing. I am not able to check what may be the issue.
![IMG_20200505_162519](https://user-images.githubusercontent.com/28186433/81059439-0d04cb00-8eee-11ea-84a2-02fcd4100168.jpg)
Please help!

**Comment by mikehardy** [comment] 2020-05-05 13:41
Please tell us how it worked when you tried the example app

**Comment by kindacoder** [comment] 2020-05-06 01:31
@mikehardy Thank you for replying. I have used the class component example but have not stored the credentials and all into the local state because I don't need them. I just want to get the user data like email and Name and pass this data to server.

**Comment by Baksha2008** [comment] 2020-05-06 16:52
I have the same problem. Does anyone have a solution?

**Comment by mikehardy** [comment] 2020-05-06 16:55
This doesn't happen to anyone except you two, I believe it is a project integration error. I don't say that lightly - it is just that Apple makes it so there are about 20 things you have to do in their developer web app plus changes to make in your Xcode project files and provisioning profiles. I suspect one of them is missed. I can't reproduce this and neither has anyone else so far, it works for us, sorry

**Comment by VooduVibe** [comment] 2020-05-08 10:29
**@kindacoder** and **@Baksha200**8 were you able to identify and fix the problem. I am experiencing the same difference in behavior between the emulator and a physical device.

**@mikehardy**, would really appreciate your guidance in relation to the following question about the expected behaviour during sign-up versus subsequent sign-in. Is the process-flow for sign-up versus subsequent sign-in designed to be the same? Or is there a simplified flow for subsequent sign-ins?

On my emulator the same "sign-up" process is repeated no matter how many times I sign in (this is illustrated in @kindacoder's 1st image above). Is this the correct behaviour?

On my physical test device, the first implementation of the authentication process executes the "sign-up"  flow (image 1) whereas a subsequent sign-in implements a simplified flow (this is illustrated in @kindacoder's 2nd image above). Which of these is the expected flow given that the Keychain log for both the emulator and the device contain a record that my app uses Apple ID?

My issue is that a subsequent sign-in on my device does not lead me to to my app homepage but rather it remains on the sign-in page.

Any help would be highly appreciated.

**Comment by mikehardy** [comment] 2020-05-08 15:05
So @VooduVibe is it working as you like on a real device? If so there is no issue. The simulators for iOS are a poor substitute for the real thing and the metric is real device behavior. Works on real device -> no issue -> no action item here

**Comment by VooduVibe** [comment] 2020-05-08 15:23
Hi @mikehardy... thank you for responding. The flow works on the physical device as described in my earlier write-up. So I believe you are confirming that this is indeed the correct workflow, which is fine. Thank you.

The problem I am faced with now is that on the 2nd sign-in (authentication) on the device, it does **not** proceed to my app's homepage (as it did in the first sign-up), it just closes the apple authentication page (image 2 above) and remains on my app's sign in page.

I am wondering whether I am missing something here. I'm just hoping you could at least point me in the right direction. Your advice would be greatly appreciated.

**Comment by mikehardy** [comment] 2020-05-08 16:22
Sorry, no idea. That's app specific @VooduVibe - something about your code that is responding to the login must not be correct. My project looks at the return value and behaves accordingly, forwards on just fine

**Comment by mikehardy** [comment] 2020-05-08 16:23
I don't think there is an action item here for the module so discussion can continue but the issue isn't an issue per se -> closing

**Closed by mikehardy** 2020-05-08 16:23 UTC

**Comment by VooduVibe** [comment] 2020-05-08 17:20
Thanks @mikehardy.. appreciate the feedback.

**Comment by gothraven** [comment] 2020-05-14 14:14
I'm also having the same issue, @VooduVibe did you find any solution ? In the real device I never get the sign-up flow, i'm always getting the sign-in flow

**Comment by enrickdl** [comment] 2020-07-10 19:34
I'm also having a similar issue. When I use touch ID to sign up, I don't receive the fullName, only the user field and the identityToken. Basically, when I sign up in the simulator, I get all the users data.

And when we decode the identityToken, we can only get the user email. Any idea on how to get the fullName using touch ID?

**Comment by lebtonya** [comment] 2020-07-30 17:14
I also struggle with this problem, the answer I found -> https://stackoverflow.com/questions/57545635/cannot-get-name-email-with-sign-in-with-apple-on-real-device

So it's actu proper behaviour 🤷

**Comment by enrickdl** [comment] 2020-07-30 18:05
I had to add a verification logic inside the app to check if the fullName was provided, otherwise, the user is navigated to another screen where he/she can input their names.
