### ISSUE TITLE
Apple login doesn't return email data and user info

### ISSUE THREAD

**Issue by rifkiandriyanto** [invertase/react-native-apple-authentication#257] opened 2022-01-12 06:33 UTC
I am not getting user info from apple login.
System:
    OS: macOS 12.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 20.66 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.2.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.4 - /usr/local/bin/npm
    Watchman: 2021.12.06.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 23, 26, 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-27 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6821437
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.66.4 => 0.66.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Response apple login:
{
  "user ": "000XXX.82bf1fa2XXXd4473ea745b9ac306dXXX.04XX ",
  "email ": null,
  "authorizedScopes ": [],
  "fullName ": {
    "namePrefix ": null,
    "givenName ": null,
    "familyName ": null,
    "nickname ": null,
    "middleName ": null,
    "nameSuffix ": null
  },
  "identityToken ": "eyJraWQiOiJlWGF1bm1MIiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJodHRwczovL2FwcGxlaWQuYXBwbGUuY29tIiwiYXVkIjoiY29tLnN5b29iZS5hcHAiLCJleHAiOjE2NDIwNTAyMDYsImlhdCI6MTY0MTk2MzgwNiwic3ViIjoiMDAwMTM1LjgyYmYxZmEyMzVkNDQ3M2VhNzQ1YjlhYzMwNmRmOTZhLjA0MzUiLCJub25jZSI6Ijg3NjI3YzZlOTAwZDk2ZmZkYjI3NzVlNzdiZTFkYTJlMGY4OTYxY2U1NTM5NTQ2MmY5MmJmOTk0YzQ5ZDBiZjAiLCJjX2hhc2giOiJsVXlpU2lON2ZwS0oyeHpOU2JDanpRIiwiZW1haWwiOiJkZXZpbGluZ2xpbmcxN0BpY2xvdWQuY29tIiwiZW1haWxfdmVyaWZpZWQiOiJ0cnVlIiwiYXV0aF90aW1lIjoxNjQxOTYzODA2LCJub25jZV9zdXBwb3J0ZWQiOnRydWV9.niN4kyJcRscclXPefu-FFyH5Tr1pYdGLIFspJ9_U9WB482HCx_1_gjzkQPN1k-s9MImkReSUCQmgCQcx5k1qv2VChy9-S33BRRGX8Ot5q5v8r0_T55eTKS0nVyKG7aG3nHFlbabX1XHJipt4IKX45bZA0RGY3Ox5ojQgieY5qJ0Zgbu1D4QnWQ0ivZ17bAjOmfP1eDuwYXPQ4GvZ05ivrKuaiVEPQGlCr4b8vmxdENEiq-AsVa2nf-Ro3VEAQX1BKOAVPx1Pu5jngnGiJT3ffVAaKnkrh3_vRU6qWUkXFai83cKClAxbaD5ZWEGwMxF7sDWfBrB-nUX5o8eGGKytNA ",
  "authorizationCode ": "c728fa7cc630b495db5816a47ae677259.0.srtv.5ksvwBuPaTuAlAKna21vOg ",
  "realUserStatus ": 1,
  "state ": null,
  "nonce ": "1JUfV5XQQTgta611wD7BssESfF_cstE0 "
}

**Comment by mikehardy** [comment] 2022-01-12 12:37
Duplicate of many issues, all answered, please search the list

**Closed by mikehardy** 2022-01-12 12:37 UTC
