### ISSUE TITLE
Customise locale for text

### ISSUE THREAD

**Issue by kromsik** [invertase/react-native-apple-authentication#54] opened 2020-03-25 15:25 UTC
Cannot provide my own text if Button used in multi-lingual app
![Screenshot 2020-03-25 at 18 24 20](https://user-images.githubusercontent.com/33729094/77553558-041fe300-6ec6-11ea-9f01-4f637503f1f4.png)

**Comment by mikehardy** [comment] 2020-03-25 16:46
This is a limitation of the library, it is not specific to this module.
The text will be localized according to the system device language, I have tested this and it works, there is not other way to provide text

**Comment by kromsik** [comment] 2020-03-26 05:25
The text will be localized according to the system device language, I have tested this and it works, there is not other way to provide text

Unfortunately this is not how it works

**Comment by mikehardy** [comment] 2020-03-26 14:27
I am unable to reproduce - please show a reproduction based on the example (maybe upload it to youtube) where you go from installing the example project to starting it in English, to closing it, setting system language to Spanish, then starting it in Spanish (my case, where I can't reproduce) to closing it and setting system language to Russian (I am guessing this is your case?) and starting it again.

For me, switching system language and restarting the app shows me translated buttons.

**Comment by aaser5** [comment] 2020-03-26 14:33
Greetings,

I'm also testing on a simulator, I have changed the language to French but unfortunately, the button language didn't change 

so any help with that ?

**Comment by mikehardy** [comment] 2020-03-26 14:38
I literally just tested it, it works. Start app while system language set to English. Button in English. Swipe app away. Change system language to Spanish. Open app. Button in Spanish.

**Comment by aaser5** [comment] 2020-03-26 15:17
I have tested Spanish now and closed the app and rerun it but also the same behavior 
![Simulator Screen Shot - iPhone 11 - 2020-03-26 at 17 15 36](https://user-images.githubusercontent.com/22647956/77663218-7f949980-6f85-11ea-86a8-7adf2db0e51f.png)
![Simulator Screen Shot - iPhone 11 - 2020-03-26 at 17 15 21](https://user-images.githubusercontent.com/22647956/77663225-828f8a00-6f85-11ea-81ed-688a1ea284ce.png)

**Comment by aaser5** [comment] 2020-03-26 16:54
I have figured that we have to change the Localization native development region in info.plist and it's now fixed thanks for your help appreciated

**Comment by kromsik** [comment] 2020-03-26 17:48
> I have figured that we have to change the Localization native development region in info.plist and it's now fixed thanks for your help appreciated

Can you please clarify your changes? I have a locales provider and it does change app locales, but text on button is not changed

![image](https://user-images.githubusercontent.com/33729094/77679034-11f76600-6fa3-11ea-9ca6-639560e5254b.png)

**Comment by mikehardy** [comment] 2020-03-26 17:54
@kromsik / @aaser5 this may be something we need to document! Your comment gave me a hint - my plist files are in fact localized, I have en and es plist localization, so maybe that is why it worked for me? I tested by changing to 'it' (I do not have my plist files localized to Italian) and...it did not work!

So the conclusion seems to be if you attempt to switch the phone to a language you have natively (i.e., in plist files) translated to, it will work, otherwise you will get your default language.

@kromsik - can you verify this hypothesis? what language is your app in natively - the guess is that you don't have Russian localization in the plist files and if you either add it or switch to it it will work. If that's the case we should document that.

**Comment by kromsik** [comment] 2020-03-26 18:23
> Your comment gave me a hint - my plist files are in fact localized, I have en and es plist localization, so maybe that is why it worked for me? I tested by changing to 'it' (I do not have my plist files localized to Italian) and...it did not work!

I guest this is it! Can you please share your plist file?

**Comment by mikehardy** [comment] 2020-03-26 18:33
@kromsik I'm not sure if the contents are useful, but the setup is like this:

```
mike@isabela:~/work/Kullki/ksocialscore/packages/public-app (rebranding) % find ios |grep lproj
ios/KScoreApp/en.lproj
ios/KScoreApp/en.lproj/InfoPlist.strings
ios/KScoreApp/es.lproj
ios/KScoreApp/es.lproj/LaunchScreen.strings
ios/KScoreApp/es.lproj/InfoPlist.strings
ios/KScoreApp/Base.lproj
ios/KScoreApp/Base.lproj/LaunchScreen.xib

```

If I use 'en' or 'es' languages as system language, I get a translated button automatically, if I attempt 'it', I do not get 'it', I get one of the languages I do have.

**Comment by sercanuste** [comment] 2020-04-10 13:17
Hi,

Changing CFBundleDevelopmentRegion at Info.plist changes default language of apple button. And adding CFBundleAllowMixedLocalizations allows multi-language support. By this way there is no need for localized Info.plist.

```XML
<key>CFBundleDevelopmentRegion</key>
<string>fr</string>
<key>CFBundleAllowMixedLocalizations</key>
<string>true</string>
```

**Closed** 2020-05-02 14:34 UTC
Labels: no-reproduction

**Comment by douglasjunior** [comment] 2020-12-28 19:56
```xml
  <key>CFBundleAllowMixedLocalizations</key>
  <string>true</string>
```

Fixes for me.
